/***********************************************************************************************************************
* DISCLAIMER
* This software is supplied by Renesas Electronics Corporation and is only 
* intended for use with Renesas products. No other uses are authorized. This 
* software is owned by Renesas Electronics Corporation and is protected under 
* all applicable laws, including copyright laws.
* THIS SOFTWARE IS PROVIDED "AS IS" AND RENESAS MAKES NO WARRANTIES REGARDING 
* THIS SOFTWARE, WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING BUT NOT 
* LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE 
* AND NON-INFRINGEMENT.  ALL SUCH WARRANTIES ARE EXPRESSLY DISCLAIMED.
* TO THE MAXIMUM EXTENT PERMITTED NOT PROHIBITED BY LAW, NEITHER RENESAS 
* ELECTRONICS CORPORATION NOR ANY OF ITS AFFILIATED COMPANIES SHALL BE LIABLE 
* FOR ANY DIRECT, INDIRECT, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES FOR 
* ANY REASON RELATED TO THIS SOFTWARE, EVEN IF RENESAS OR ITS AFFILIATES HAVE 
* BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
* Renesas reserves the right, without notice, to make changes to this software 
* and to discontinue the availability of this software.  By using this software, 
* you agree to the additional terms and conditions found by accessing the 
* following link:
* http://www.renesas.com/disclaimer
*
* Copyright (C) 2012 Renesas Electronics Corporation. All rights reserved.
***********************************************************************************************************************/

/***********************************************************************************************************************
* File Name    : interrupt_handlers.c
* Version      : 1.00
* Device(s)    : R5F10RLC
* Tool-Chain   : GNURL78 v12.03
* Description  : This file contains the interrupt handlers.
* 				 This file was generated by e2studio.
* Creation Date: 21/01/2013
***********************************************************************************************************************/

/* Header file includes the attributes directive to
   ensure the functions are defined as interrupt handlers */
#include "interrupt_handlers.h"

/*
 * INT_WDTI (0x4)
 */
void INT_WDTI (void) { }

/*
 * INT_LVI (0x6)
 */
void INT_LVI (void) { }

/*
 * INT_P0 (0x8)
 */
//void INT_P0 (void) { }

/*
 * INT_P1 (0xA)
 */
void INT_P1 (void) { }

/*
 * INT_P2 (0xC)
 */
void INT_P2 (void) { }

/*
 * INT_P3 (0xE)
 */
//void INT_P3 (void) { }

/*
 * INT_P4 (0x10)
 */
//void INT_P4 (void) { }

/*
 * INT_P5 (0x12)
 */
void INT_P5 (void) { }

/*
 * INT_DMA0 (0x14)
 */
void INT_DMA0 (void) { }

/*
 * INT_DMA1 (0x16)
 */
void INT_DMA1 (void) { }

/*
 * INT_CSI00/INT_ST0 (0x18)
 */
void INT_ST0 (void) { }
//void INT_CSI00 (void) { }

/*
 * INT_CSI01/INT_SR0 (0x1A)
 */
void INT_SR0 (void) { }
//void INT_CSI01 (void) { }

/*
 * INT_SRE0/INT_TM01H (0x1C)
 */
//void INT_TM01H (void) { }
//void INT_SRE0 (void) { }

/*
 * INT_TM00 (0x20)
 */
//void INT_TM00 (void) { }

/*
 * INT_TM03H (0x24)
 */
void INT_TM03H (void) { }

/*
 * INT_IICA0 (0x26)
 */
void INT_IICA0 (void) { }

/*
 * INT_TM01 (0x28)
 */
void INT_TM01 (void) { }

/*
 * INT_TM02 (0x2A)
 */
//void INT_TM02 (void) { }

/*
 * INT_TM03 (0x2C)
 */
void INT_TM03 (void) { }

/*
 * INT_AD (0x2E)
 */
//void INT_AD (void) { }

/*
 * INT_RTC (0x30)
 */
//void INT_RTC (void) { }

/*
 * INT_IT (0x32)
 */
//void INT_IT (void) { }

/*
 * INT_KR (0x34)
 */
void INT_KR (void) { }

/*
 * INT_TM04 (0x3C)
 */
void INT_TM04 (void) { }

/*
 * INT_TM05 (0x3E)
 */
void INT_TM05 (void) { }

/*
 * INT_TM06 (0x40)
 */
void INT_TM06 (void) { }

/*
 * INT_TM07 (0x42)
 */
void INT_TM07 (void) { }

/*
 * INT_LCD0 (0x44)
 */
void INT_LCD0 (void) { }

/*
 * INT_P6 (0x46)
 */
void INT_P6 (void) { }

/*
 * INT_P7 (0x48)
 */
void INT_P7 (void) { }

/*
 * INT_MD (0x4A)
 */
void INT_MD (void) { }

/*
 * INT_FL (0x4C)
 */
void INT_FL (void) { }

/*
 * INT_BRK_I (0x7E)
 */
void INT_BRK_I (void) { }
